### ISSUE TITLE
Reference tokens auto-referencing themselves in the exported JSON

### ISSUE THREAD

**Issue by exhtml** [tokens-bruecke/figma-plugin#1]
Hi! I've testing the plugin and it works perfect! but I've detected that when using references, in the exported JSON you are auto-referencing the current token instead of the correct reference token. Example with a `Semantic Color` collection with tokens referencing `Primitive Color` collection:

```json
{
"Semantic: Color": {
  "Light": {
    "Brand": {
      "Red (TR-600)": {
         "$value": "{Semantic: Color.Light.Colors.Red.600}",
         "$type": "color",
       //...
},

"Primitive: Color": {
  "Colors": {
    "Red": {
      "600": {
        "$value": "hsla(4, 77%, 48%, 1)",
        "$type": "color",
        // ...
        "$extensions": {
          "variableId": "VariableID:8414:43621",
          "aliasPath": "{Primitive: Color.Colors.Red.600}"
         }
},

```
Thanks for checking it!

**Comment by PavelLaptev** [comment]
@exhtml thank you for reporting this. Just published a new version. Can you please check if it works for you?
(You'll need to refresh the tab where you want to run the plugin in order to reset the cached version)

**Comment by exhtml** [comment]
Hi @PavelLaptev , now seemst to make the correct export, thank you very much for your time!
On other subject, are you planning to implement any kind of parser to make the output JSON compatible with Style Dictionary? Something similar to what's explained greatly by Lukas Oppermann here https://lukasoppermann.medium.com/w3c-design-tokens-with-style-dictionary-f7ff5f2ba98c
There's something similar for Tokens Studio: https://github.com/tokens-studio/figma-plugin/tree/main/token-transformer
I'll give it a try and let you know!

**Comment by PavelLaptev** [comment]
@exhtml sure thing. Currently, I'm working with style dictionary and planning to add my workarounds this week. So, stay tuned 🙁
