### ISSUE TITLE
Drop shadow effects: how to support multiple shadows in one effect?

### ISSUE THREAD

**Issue by JeroenRoodIHS** [tokens-bruecke/figma-plugin#11]
As the title says: I am wondering how I could support multiple shadows in one drop shadow effect. I take cues from Material Design with supporting shadows: they have three shadows for one definition of elevation, which I derived my own set of drop shadow effects from:

<img width="419" alt="image" src="https://github.com/tokens-bruecke/figma-plugin/assets/37173130/38d615f5-775c-438c-936b-51f470cee5da">

Currently, only one of the drop shadows ends up in my tokens.json file.

<img width="401" alt="image" src="https://github.com/tokens-bruecke/figma-plugin/assets/37173130/5174698b-adfa-41bf-994c-38f5f359cbff">

Is it possible to support multiple drop shadows in my tokens.json?

**Comment by JeroenRoodIHS** [comment]
I thought to myself: why not looking at the code, to see if multiple drop shadows are supported already, and I am not missing something. Turns out that only one part of an effect is considered, by selecting `effect[0]`, rather than considering the drop shadow effect as an array.

I am not aware of how effects are passed to the plugin, but I assumed that any drop shadow would be an entry of the `effect` array. That is why I forked this repo and created a PR to submit a suggestion for handling the drop shadow effects.

This is my PR: https://github.com/tokens-bruecke/figma-plugin/pull/12/commits/35acf360d7a2f2fd7b33d17561c304005fda15f0

Please do note that a guide for contribution to this repo is still WIP. I don't know how to properly contribute to this repo. Consider my PR as a suggestion, and use it whichever way you like to. I think that treating the drop shadow effects as arrays and exporting them as such may be the best way to go.

I am curious to any feedback.

**Comment by dev-nicolaos** [comment]
Agreed it'd be good support multiple shadows in the same token. I know its already been linked to in the PR, but for those searching in the future here is [the relevant spec issue](https://github.com/design-tokens/community-group/issues/100). 

It looks like [Cobalt implemented support](https://github.com/drwpow/cobalt-ui/pull/114) for this recently. It'd be nice if the implementation was interoperable.

**Comment by PavelLaptev** [comment]
Just merged this PR https://github.com/tokens-bruecke/figma-plugin/pull/12

**Comment by dev-nicolaos** [comment]
Looks like the release (0b64358f7e8a7cbc2f4f64ce4e9f18bc736b8282) that implemented this fix didn't get tagged in GitHub. I don't know if anyone consumes the package that way so its not a huge deal. However, this does mean the repo's homepage looks misleading since the other releases were tagged. The "Releases" section on the right still shows 2.0.0 as being the most recent release.

Other than that, it looks like this issue could be closed.

**Comment by PavelLaptev** [comment]
You right, that's my bad. I'll fix it asap

**Comment by PavelLaptev** [comment]
done https://github.com/tokens-bruecke/figma-plugin/releases/tag/2.1.0

**Comment by dev-nicolaos** [comment]
Nice! I think this issue can get closed then.
