### ISSUE TITLE
Use of plugin within different teams and projects

### ISSUE THREAD

**Issue by heibjornendre** [tokens-bruecke/figma-plugin#15]
It seems like the plugin saves some sort of meta data which is not updated when going between different projects and teams in Figma. Working for an agency and going back and forth between multiple clients, the "Add styles to" plugin option and `variableCollections` in the JSON seems to refer to the very first project I tested it in.

This is a **very** handy plugin and 'm super happy with finding it after testing a bunch of different Figma export plugins. As a designer I can see a very smooth collaboration with the frontend developers using this plugin.

**Comment by PavelLaptev** [comment]
Thank you @heibjornendre that's very nice to hear 🙂
