### ISSUE TITLE
Effects key label is uppercase

### ISSUE THREAD

**Issue by cailborg** [tokens-bruecke/figma-plugin#2]
Using the included styles toggle will output the name of the style included in uppercase? Is this the intended output? The rest of my keys are all lowercase

```
"Effects": {
      "shadow": {
        "0": {
          "type": "shadow",
          "value": {
            "inset": false,
            "color": "#1e1e1e00",
            "offsetX": "0px",
            "offsetY": "0px",
            "blur": "0px",
            "spread": "0px"
          }
        },

```

**Comment by PavelLaptev** [comment]
@cailborg thank you for the question.
You can rename style groups. I added this GIF preview into the README file.

![rename-styles](https://github.com/tokens-bruecke/figma-plugin/assets/18498712/6745339c-5aea-4734-9133-b1373f743925)

**Comment by cailborg** [comment]
Fantastic thanks.
