### ISSUE TITLE
Alias resolution with Style Dictionary

### ISSUE THREAD

**Issue by cailborg** [tokens-bruecke/figma-plugin#4]
I've noticed your plugin adds the alias for a token as
```
"$value": "{base.primary.yellow}"
```

When you try to resolve aliases in style dictionary i'm getting a blank output file

Should the plugin output an alias path the same as the [style dictionary example](https://github.com/amzn/style-dictionary/tree/main/examples/advanced/referencing_aliasing)?

```
"$value": "{base.primary.yellow.value}"
```

**Comment by PavelLaptev** [comment]
Interesting. Thanks for feedback @cailborg 
I'll check it out.
Which version of Style Dictionary do you use?

**Comment by cailborg** [comment]
Just `latest` at the moment, so `3.8.0`

**Comment by PavelLaptev** [comment]
Thank, and for which platform, CSS?
I'll check it in the morning 🙂

**Comment by cailborg** [comment]
Yep CSS and SCSS

**Comment by PavelLaptev** [comment]
Should work fine, without `value` at the end. I've checked a test JSON file with Style Dictionary playground — [here is a link](https://www.style-dictionary-play.dev/#project=3Vhbb9owFP4rVbanikG4lcsboqWrRrVqrfawBlUmOQFT5yLbqYoQ/312Qu4hAbWdRhME2Of4xN/nz8d2NoqOqNGQX3XuPIPN6ivm2MpQ2Wj22ZmmiALWNWV45pdlje4QhyZqZN0c6c8L6ni2kTL4Jo9zx85US4NLsYXoOmeRNgNM5BFeYJPWF0Q8kDZN2cwRg7ruUETqA3WrKbW8O1+7O+9d1wt8DGA6xS7HQVc1pdCL6Y4LTDo8aspoOn26H/+8u7rXlFmBM7xyQacIyAphBEAoRnMCN0bw0N9h+XLYHLZEJzJttumKbS3L29J5AXoca/1/y9r999Hd1dPkZjoVvsI4+TW6DcsfwWK7msVkMU2ppjgeJ9iG9xCpDR7/hDJtXny0TkPi+p+MuN6R0owL0d/dH/8nYFmAcJEOqYwNBCyweSZnE0QXkEvXCfY7ffc1RVOSagNbAfqMRznRB1JcSm4Frd0kqzFRtRi4BQb2rDLkrc4pIr+oRM4sREgZ8JMc8V4x7oKpIdNJambsUktmZvTUMo6+zE157+Upn4T+A46azUpx9MtRI13eJ4ZarUQ9KEfdRfI+LdSD0vlQi/fxRyvf7EEXuiemgc5blQ/GXJ2rJ4a6/Vbl6/P+oD84MdStg5eCrxZwlFoLPAaXD+PrH7D2n2siwiAxWQTcW8fYoV9CvE7GfRo7hIDOw54/RqfnWrwtq0XL0CwOTgFxMEZ8t/tQW+1vav9bq/Wg9oad1lBt1gf99p8Am0AhPkot6FLD3yEXntyz5/Tc8ierFhStczIgeLHkhdzH8hj7V4ru1CAWbrKyQQb+tT+IgehzRYimf1WKnYJRqvbJRBVXHCbZdkEB7NLWqirbJ1onBSfGKxot07H5oaMlfXOvWVjpjn3jR6n7mhCIt8V4GOiObeRfvewN5ROwJxgHyvFRsdC6Lsd1W0GXbeJF7l2UR4OjzWNI0vl54zxJaBB0tpvkLkHcdKjFUsTqjGV4FXtAm0nHa/EOy90lOOmVAOpSMPFrYGNGyjT3MDHuEF8GVr/YEO0bKS8TkzD5RTRlhC0SKMc2ihPoU5haWD3dn1Ai1EI86m8j8i6cD7PsDmB1CA8rVo119Q5QY6SrcqAr9IKCdaYB7KIUaUJQFBkYl2RL354+Gzh2NlsmNB3N9phOZu139w9W2V5t/wI=)
Looks like the reason in something else.

---

Also, I made Style Dictionary utils package. So, you can try to transform your tokens with it — https://github.com/tokens-bruecke/sd-utils

Here is a test repo with Github Actions — https://github.com/tokens-bruecke/tokens-deploy-with-actions

**Comment by PavelLaptev** [comment]
I made a custom build. In this build, the plugin will add `.value` at the end of the alias string.
Can you check if it works for you?

[plugin-test-2.zip](https://github.com/tokens-bruecke/figma-plugin/files/12406619/plugin-test-2.zip)

**Comment by PavelLaptev** [comment]
Also, might be the reason in this
`"$value": "{base.primary.yellow.value}"`
that you're using DTCG format `$value`

**Comment by PavelLaptev** [comment]
Added `value` or `$value` (if it's the `DTCG` format) at the end of the alias paths.

**Comment by dev-nicolaos** [comment]
@PavelLaptev wouldn't it be more appropriate for this change to live in the style dictionary utils? [The alias example provided by the spec](https://tr.designtokens.org/format/#aliases-references) does not append `value` to the end of an alias. Cobalt's (a DTCG parser) example matches the spec. Style dictionary is the only place I've seen so far where `value` is appended.

**Comment by PavelLaptev** [comment]
@dev-nicolaos thank you for your feedback. I think you're right. I'll leave adding `value` at the end of an alias optional.

**Comment by PavelLaptev** [comment]
@dev-nicolaos updated. It's now optional

![image](https://github.com/tokens-bruecke/figma-plugin/assets/18498712/6d198c51-d30d-4fa3-96f0-7c031e50bcfd)
